job_queue: dell-pro-rugged-13-ra13250-0cda-c34190
provision_data:
  url: https://tel-image-cache.canonical.com/oem-share/somerville/releases/noble/oem-24.04a/20241006-108/somerville-noble-oem-24.04a-20241006-108.iso
reserve_data:
  ssh_keys:
    - lp:pe-bot
  timeout: 60
output_timeout: 3600
