job_queue: 202504-36638
provision_data:
  url: https://tel-image-cache.canonical.com/oem-share/sutton/releases/noble/oem-24.04c/20250814-43/sutton-noble-oem-24.04c-20250814-43.iso
reserve_data:
  ssh_keys:
    - lp:wfrench
  timeout: 60
output_timeout: 3600
