job_queue: 202506-36888
provision_data:
  url: https://tel-image-cache.canonical.com/oem-share/sutton/releases/noble/oem-24.04b-proposed/20250620-519/sutton-noble-oem-24.04b-proposed-20250620-519.iso
reserve_data:
  ssh_keys:
    - lp:wfrench
  timeout: 1800
global_timeout: 2400
