job_queue: REPLACE_QUEUE
output_timeout: 7200
provision_data:
  url: REPLACE_IMAGE_URL
test_data:
  attachments:
    - local: REPLACE_ATTACHMENT
      agent: "checkbox-npu.snap"
    - local: ".github/testflinger/check-npu-fw.sh"
      agent: "check-npu-fw.sh"
    - local: ".github/testflinger/run-checkbox-npu.sh"
      agent: "run-checkbox-npu.sh"
  test_cmds: |

    set -x

    # retrieve the tools installer
    curl -Ls -o install_tools.sh https://raw.githubusercontent.com/canonical/hwcert-jenkins-tools/main/install_tools.sh
    # install the scriptlets and other tools on the agent and the device, as necessary
    export TOOLS_PATH=tools
    source install_tools.sh $TOOLS_PATH

    # ensure device is available before continuing
    wait_for_ssh --allow-degraded

    echo
    echo "====== TARGET DEVICE CONNECTION INFO ======"
    echo
    echo DEVICE_IP: ubuntu@$DEVICE_IP
    echo
    echo "==========================================="
    echo

    # Avoid GPG errors on old unsupported versions of Chrome, which we don't test anyway
    _run sudo rm /etc/apt/sources.list.d/google-chrome.list

    _run sudo snap refresh
    _run sudo snap install intel-npu-driver --channel latest/edge

    echo "[INFO]: Sleeping for 60 seconds to ensure the firmware search path is updated."
    sleep 60

    _put attachments/test/check-npu-fw.sh :/home/ubuntu/check-npu-fw.sh
    _run bash check-npu-fw.sh

    _run sudo snap install checkbox24
    _put attachments/test/checkbox-npu.snap :/home/ubuntu/checkbox-npu.snap
    _run sudo snap install --dangerous --classic /home/ubuntu/checkbox-npu.snap

    _put attachments/test/run-checkbox-npu.sh :/home/ubuntu/run-checkbox-npu.sh

    # Run the validation twice:
    #
    # Run 1: original debs and kernel from the certified image
    # Run 2: upgraded debs and kernel, following a reboot
    #
    _run sudo bash run-checkbox-npu.sh

    _run sudo apt-get update
    _run sudo apt-get -y upgrade
    _run sudo reboot
    wait_for_ssh --allow-degraded

    _run sudo bash run-checkbox-npu.sh
