job_queue: REPLACE_QUEUE
output_timeout: 7200
provision_data:
  url: REPLACE_IMAGE_URL
test_data:
  attachments:
    - local: REPLACE_ATTACHMENT
      agent: "checkbox-npu.snap"
    - local: ".github/testflinger/check-npu-fw.sh"
      agent: "check-npu-fw.sh"
  test_cmds: |

    set -x

    # retrieve the tools installer
    curl -Ls -o install_tools.sh https://raw.githubusercontent.com/canonical/hwcert-jenkins-tools/main/install_tools.sh
    # install the scriptlets and other tools on the agent and the device, as necessary
    export TOOLS_PATH=tools
    source install_tools.sh $TOOLS_PATH

    # ensure device is available before continuing
    wait_for_ssh --allow-degraded

    echo
    echo "====== TARGET DEVICE CONNECTION INFO ======"
    echo
    echo DEVICE_IP: ubuntu@$DEVICE_IP
    echo
    echo "==========================================="
    echo

    _run sudo snap install intel-npu-driver --channel latest/edge

    echo "[INFO]: Sleeping for 60 seconds to ensure the firmware search path is updated."
    sleep 60

    _put attachments/test/check-npu-fw.sh :/home/ubuntu/check-npu-fw.sh
    _run bash check-npu-fw.sh

    _run sudo snap install checkbox24
    _put attachments/test/checkbox-npu.snap :/home/ubuntu/checkbox-npu.snap
    _run sudo snap install --dangerous --classic /home/ubuntu/checkbox-npu.snap

    _run sudo usermod -a -G render ubuntu
    _run sudo chown root:render /dev/accel/accel0
    _run sudo chmod g+rw /dev/accel/accel0

    _run sudo apt-get install -y curl
    _run checkbox-npu.install-full-deps
    echo
    echo "========= Checkbox NPU ========="
    echo "====== DEVICE KERNEL INFO ======"
    echo
    _run uname -a
    echo
    echo "==========================================="
    echo
    _run checkbox-npu.test-runner-automated

    # Upgrade apt packages, primarily to revalidate against a newer kernel
    _run sudo apt-get update
    _run sudo apt-get -y upgrade
    _run sudo reboot
    wait_for_ssh --allow-degraded

    _run checkbox-npu.install-full-deps
    echo
    echo "========= Checkbox NPU ========="
    echo "====== DEVICE KERNEL INFO ======"
    echo
    _run uname -a
    echo
    echo "==========================================="
    echo
    _run checkbox-npu.test-runner-automated