name: Build snap and run smoke tests
on:
  workflow_dispatch:
  push:
    paths:
      - 'snap/**'
      - 'bin/**'
      - '.github/workflows/smoke-tests.yaml'
    branches:
      - main
      - frenchwr/testflinger-integration # temporary
  pull_request:
    paths:
      - 'snap/**'
      - 'bin/**'
      - '.github/workflows/smoke-tests.yaml'
    branches:
      - main

env:
  SNAP_ARTIFACT_NAME: intel-npu-driver-snap
  SNAP_FILE: intel-npu-driver.snap

jobs:
  snap-build:
    name: Build snap
    runs-on: [self-hosted, linux, X64, xlarge, jammy]
    steps:
      - uses: actions/checkout@v4
      - uses: snapcore/action-build@v1
        id: snapcraft
        with:
          snapcraft-args: "-o ${{ env.SNAP_FILE }}"
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.SNAP_ARTIFACT_NAME }}
          path: ${{ steps.snapcraft.outputs.snap }}

  snap-test:
    name: Install and verify snap
    runs-on: ubuntu-24.04
    needs:
      - snap-build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.SNAP_ARTIFACT_NAME }}
      - name: Install snap
        shell: bash
        run: |
          sudo snap install --dangerous ${{ env.SNAP_FILE }}
          snap list
      - name: Check autoconnecting snap interfaces
        shell: bash
        run: |
          snap connections intel-npu-driver | grep -w custom-device
          snap connections intel-npu-driver | grep -w kernel-firmware-control
          snap connections intel-npu-driver | grep -w kernel-module-control
      - name: Verify that the load-npu-firmware service is enabled
        shell: bash
        run: |
          snap services intel-npu-driver.load-npu-firmware | grep -w enabled
      - name: Verify that the user mode driver validation tool is deployed in the snap
        shell: bash
        run: |
          echo "Checking for the user mode driver command in the snap..."
          command -V intel-npu-driver.vpu-umd-test