#!/bin/bash

if [ "${SNAP_UID}" -ne 0 ]; then
  >&2 echo "Please run as root"
  exit 1
fi

CUSTOM_FW_PATH_FILE=/sys/module/firmware_class/parameters/path
echo -n " " > "${CUSTOM_FW_PATH_FILE}"

custom_path=$(cat ${CUSTOM_FW_PATH_FILE})
if [ -z "${custom_path}" ]; then
  echo "Custom firmware search path removed successfully."
else
  >&2 echo "Warning: custom firmware search path is non-empty: ${custom_path}"
fi

# Load NPU firmware from custom path
rmmod intel_vpu
modprobe intel_vpu

# Remove firmware binary blobs
INSTALL_DIR="${SNAP_DATA}"/intel
rm -rf "${INSTALL_DIR}"
